### PR TITLE
Update scssphp to 1.9.0 close #102

### LINKED ISSUE #102: scssphp should be updated to a maintained version
This package currently locks the 1.4.0 release of scssphp. The latest version is 1.9.0 (with 1.10.0 being in progress). It would be great to use the latest version.

Disclaimer: I don't use this package. I'm one of the scssphp maintainers, and I found this package when investigating why some older versions of scssphp were still seeing a non-negligeable amount of installs in the stats.

### PR DESCRIPTION
**Pull request by tronsha**

### CODE REVIEW

**Review by Macavity — APPROVED** [review]

**Comment by Macavity** [comment]
Seems you were faster :D

**Comment by stof** [comment]
Maybe you should use a semver range (`^1.9`) instead of pinning an exact version (it may depend on the needs of the project)

**Comment by Macavity** [comment]
@stof While going through the changelogs I saw at least one case of a breaking change as part of a minor version release. The ServerException was removed in 1.5.0. Although scssphp might not have used the class - an external library could have and this would have killed a process for someone targeting "^1.4".

**Comment by stof** [comment]
@Macavity all our exception classes except `SassScriptException` are tagged as `@internal`, and so should not be used directly anyway (internal APIs are not covered by backward compatibility, that's the whole point of tagging them as `@internal`).

**Comment by Macavity** [comment]
@stof That is true for the current master, but it was not true for version 1.4.1 which we were using: https://github.com/scssphp/scssphp/blob/v1.4.1/src/Exception/ServerException.php
Thus - for us that would have been a breaking change at that point in time.

But as it seems that you are aware of semver we did change the targeted version to ^1.9 😄

**Comment by stof** [comment]
Btw, ServerException was not removed in 1.5.0. It has been deprecated: https://github.com/scssphp/scssphp/blob/v1.5.0/src/Exception/ServerException.php

**Comment by Macavity** [comment]
Didn't claim it was removed. What meant to say is that in v1.4 ServerException was a normal class (not internal, not deprecated). Thus it was free to be used in depending projects as ours.
If at that time we had targeted "^1.4" in composer.json, running composer update a while later would have suddenly internalized the class - which we likely would not have realized. And then we it later got removed - broken our code.

This was mainly to counter the argument that we should not use an internal class. It wasn't internal when we used it ;-) thus making it internal and later removing it, would have been breaking change for us.

**Comment by stof** [comment]
Well, we haven't internalized it. We have deprecated it, which is exactly the way to signal that something needs to change to prepare for the next *major* version. Deprecations are precisely a tool allowing to follow semver.
See https://wouterj.nl/2021/11/deprecations-are-not-errors for an article written by another member of the Symfony core team.

**Comment by stof** [comment]
Also, given that scssphp <1.5.0 was not distinguishing properly what was internal and what was public, we haven't removed any internal API in 1.x yet (but those internal API *will* change in 2.0)

**Comment by Macavity** [comment]
I am sorry I got confused. Just earlier you stated that all other Exceptions are internal. But in 1.4 ServerException was not marked as internal. I just realized it's not marked internal even now.. so what exactly are we talking about?

**Comment by stof** [comment]
@Macavity we haven't marked it as internal because it is deprecated anyway.

And even for things we marked as internal, as we did that during the 1.x lifetime, we still don't break them in 1.x releases (however, we don't provide a migration path for them, and 2.0+ will do whatever it wants with internal APIs)

**Comment by Macavity** [comment]
Yes, you haven't removed files yet - only in untagged master, so no breaking changes so far 👍

**Pull request merged**
